#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "upstream"
fixture_input = ROOT / "fabric/src/main/java/org/valkyrienskies/mod/fabric/mixin/gatee/MixinLocalPlayerFixtureInput.java"
contact_lease = ROOT / "fabric/src/main/java/org/valkyrienskies/mod/fabric/mixin/gatee/MixinCreateContactLeaseTrace.java"
verifier = Path(__file__).resolve().with_name("prepare_vs2_26_2_m1_jump_proof.py")
source = fixture_input.read_text(encoding="utf-8")
lease_source = contact_lease.read_text(encoding="utf-8")
verifier_source = verifier.read_text(encoding="utf-8")

# Production-world #669-#673 prove the intended standing-before-walk sequencing was being
# patched at the wrong source boundary. MixinLocalPlayerFixtureInput is generated by Phase197 and
# owns the actual vanilla forward pulse; Phase165's GateEClientProbe walk-start block is a different
# class and can never occur in this source. Delay only the real Phase197/strafe-aligned pulse by one
# tick so the standing verifier gets its next callback before LocalPlayer consumes forward input.
# Production-world #707 then proves the bounded native pulse itself is being prematurely suppressed:
# walkStart=32, yet both aiStep/applyInput observe pulse=false on ticks 33-35 while the final walk
# proof remains false. Keep the start+1..+3 timing, but do not let a provisional fixture property
# cancel the only native forward+sprint input window. Final Phase188/154 acceptance still requires
# actual Minecraft sprinting plus supported displacement. Harness sequencing only: no player
# position/velocity, collision response, carry, gravity, train, or world state is changed.
walk_pulse_old = 'boolean pulse = self.tickCount >= startTick && self.tickCount <= startTick + 3 && !Boolean.getBoolean("vs2.productionFixtureWalkConfirmed");'
walk_pulse_new = 'boolean pulse = self.tickCount >= startTick + 1 && self.tickCount <= startTick + 3;'
if source.count(walk_pulse_old) != 2:
    raise SystemExit("M1 input timing expected two cumulative Phase197 forward pulse boundaries")
source = source.replace(walk_pulse_old, walk_pulse_new)

# Production-world #663 proves the negative-Z wall verifier and the actual disposable strafe
# input are pointed at opposite sides: the verifier is intentionally restored below to z=-2,
# while M1 strafe alignment still leaves yaw -90, which drives the ordinary right KeyMapping
# toward +Z. The player therefore walks off the finite +Z edge at tick 56 before jump can arm.
# Match the already-selected negative-Z proof by flipping only the test orientation to yaw +90.
# This writes view orientation only; no position, velocity, collision response, carry, gravity,
# train state, or world state is synthesized.
strafe_yaw_old = '''        if (strafeWindow && vs2$strafeStartTick == Integer.MIN_VALUE) {
            self.setYRot(-90.0F);
        }'''
strafe_yaw_new = '''        if (strafeWindow && vs2$strafeStartTick == Integer.MIN_VALUE) {
            self.setYRot(90.0F);
        }'''
if source.count(strafe_yaw_old) != 2:
    raise SystemExit("M1 negative-wall alignment expected two fixed +Z strafe orientation sites")
source = source.replace(strafe_yaw_old, strafe_yaw_new)

# Production-world #650 proves the post-walk native backward/strafe/jump sequence itself works,
# including airborne -> natural landing, but starting it at walkStart+3 consumes the exact aiStep
# tick whose later GateEClientProbe callback owns Phase188's three-tick sprint acceptance. That
# leaves the final walk marker false even though every later native input succeeds. Preserve one
# full callback boundary for the existing forward/sprint proof, then begin the disposable follow-up
# inputs on the next LocalPlayer tick. The production verifier still independently requires
# GATE_E_PHASE154_FIXTURE_WALK_CONFIRMED; no acceptance is weakened and no gameplay state is written.
old = '''    private boolean vs2$fixtureWalkSeen(LocalPlayer self) {
        if (!Boolean.getBoolean("vs2.productionFixtureWalkConfirmed")) return false;
        if (vs2$walkConfirmedTick == Integer.MIN_VALUE) vs2$walkConfirmedTick = self.tickCount;
        return true;
    }'''
new = '''    private boolean vs2$fixtureWalkSeen(LocalPlayer self) {
        if (vs2$walkConfirmedTick != Integer.MIN_VALUE) return true;
        if (Boolean.getBoolean("vs2.productionFixtureWalkConfirmed")) {
            vs2$walkConfirmedTick = self.tickCount;
            return true;
        }
        String rawStart = System.getProperty("vs2.productionFixtureWalkStartTick");
        if (rawStart == null) return false;
        try {
            int startTick = Integer.parseInt(rawStart);
            if (self.tickCount >= startTick + 4) {
                vs2$walkConfirmedTick = startTick + 4;
                return true;
            }
        } catch (NumberFormatException ignored) {
            return false;
        }
        return false;
    }'''
if source.count(old) != 1:
    raise SystemExit("M1 input timing expected one fixture walk-sequencing boundary")
source = source.replace(old, new, 1)

# Production-world #652 proves the remaining wall blocker is the fixture input boundary, not
# Create/VS2 collision. Native right-strafe is requested at tick 22 and confirmed at tick 23, but
# no further SELF aiStep movement occurs before jump even though the bounded strafe window extends
# through tick 25. The cause is the strafe-window predicate itself: confirmation immediately turns
# the window off, so the verifier can never observe sustained input into a real side wall. Keep the
# ordinary right KeyMapping active for the already-bounded window after confirmation; confirmation
# still only controls proof logging. This changes disposable input timing only and does not write
# position, velocity, collision response, carry, train, or world state.
strafe_guard_old = 'if (!vs2$fixtureWalkSeen(self) || !vs2$backwardConfirmed || vs2$strafeConfirmed) return false;'
strafe_guard_new = 'if (!vs2$fixtureWalkSeen(self) || !vs2$backwardConfirmed) return false;'
if source.count(strafe_guard_old) != 1:
    raise SystemExit("M1 sustained strafe expected one confirmation-short-circuit boundary")
source = source.replace(strafe_guard_old, strafe_guard_new, 1)

# Production-world #653 proves the remaining movement failure is at Create's native contact-lease
# expiry boundary on a fast carriage frame step. Carriage 10 applies native contact through tick 18,
# then the carriage advances about 10.9 blocks before the next client contact sample. The existing
# lease adapter tests world-space AABB overlap after that frame advance, so it returns before it can
# preserve the already-existing Create collidingEntities lease; the player then lags behind while the
# carriage continues moving. Use the exact per-carriage recent native-application identity that the
# adapter already publishes instead of stale post-frame world overlap, and allow the TAIL hook to
# catch an expiry transition occurring inside AbstractContraptionEntity.tick. This only preserves
# Create's own age-2 lease edge; it does not invent contact age 0, movement, velocity, collision,
# gravity, position, or train state.
#
# Production-world #654 then proves that per-carriage recency alone is too broad: while carriage 7
# is the active native owner, a still-recent stale lease on sibling carriage 5 is also prolonged and
# Create consequently applies both native motions in tick 39. That double native carry is the exact
# ~5.93-block local discontinuity. Preserve the extended lease only for Phase170's current native
# carriage identity; sibling leases may age out normally. This remains an ownership filter only.
lease_tail_old = '        vs2$traceContactLease("tail", false);'
lease_tail_new = '        vs2$traceContactLease("tail", true);'
if lease_source.count(lease_tail_old) != 1:
    raise SystemExit("M1 native lease expected one TAIL observation boundary")
lease_source = lease_source.replace(lease_tail_old, lease_tail_new, 1)

lease_outer_guard_old = '        if (!self.getBoundingBox().inflate(4.0).intersects(player.getBoundingBox())) return;'
lease_outer_guard_new = '''        String vs2$recentNativeTick = System.getProperty(
            "vs2.phase170NativeContactApplicationTick." + self.getId());
        String vs2$activeNativeCarriage = System.getProperty(
            "vs2.phase170NativeContactApplicationCarriageId");
        boolean vs2$recentNativeOwner = false;
        if (vs2$recentNativeTick != null
                && Integer.toString(self.getId()).equals(vs2$activeNativeCarriage)) {
            try {
                int vs2$recentNativeAge = player.tickCount - Integer.parseInt(vs2$recentNativeTick);
                vs2$recentNativeOwner = vs2$recentNativeAge >= 0 && vs2$recentNativeAge <= 20;
            } catch (NumberFormatException ignored) {
                vs2$recentNativeOwner = false;
            }
        }
        if (!vs2$recentNativeOwner
                && !self.getBoundingBox().inflate(4.0).intersects(player.getBoundingBox())) return;'''
if lease_source.count(lease_outer_guard_old) != 1:
    raise SystemExit("M1 native lease expected one stale world-overlap outer guard")
lease_source = lease_source.replace(lease_outer_guard_old, lease_outer_guard_new, 1)

lease_airborne_old = '''            boolean vs2$airborneNativeLease = !player.onGround()
                && vs2$nativeApplicationAge >= 0 && vs2$nativeApplicationAge <= 20;'''
lease_airborne_new = '''            boolean vs2$airborneNativeLease = !player.onGround()
                && vs2$recentNativeOwner
                && vs2$nativeApplicationAge >= 0 && vs2$nativeApplicationAge <= 20;'''
if lease_source.count(lease_airborne_old) != 1:
    raise SystemExit("M1 native lease expected one airborne active-owner boundary")
lease_source = lease_source.replace(lease_airborne_old, lease_airborne_new, 1)

lease_grounded_old = '''            boolean vs2$groundedNativeLease = player.onGround()
                && self.getBoundingBox().inflate(0.5).intersects(player.getBoundingBox())
                && vs2$nativeApplicationAge >= 0 && vs2$nativeApplicationAge <= 20;'''
lease_grounded_new = '''            boolean vs2$groundedNativeLease = player.onGround()
                && vs2$recentNativeOwner
                && vs2$nativeApplicationAge >= 0 && vs2$nativeApplicationAge <= 20;'''
if lease_source.count(lease_grounded_old) != 1:
    raise SystemExit("M1 native lease expected one grounded stale world-overlap guard")
lease_source = lease_source.replace(lease_grounded_old, lease_grounded_new, 1)

lease_grace_overlap_old = '''                    && (vs2$airborneNativeLease
                        || self.getBoundingBox().inflate(0.5).intersects(player.getBoundingBox()))) {'''
lease_grace_overlap_new = '''                    && (vs2$airborneNativeLease || vs2$groundedNativeLease)) {'''
if lease_source.count(lease_grace_overlap_old) != 1:
    raise SystemExit("M1 native lease expected one final stale world-overlap guard")
lease_source = lease_source.replace(lease_grace_overlap_old, lease_grace_overlap_new, 1)

# Production-world #651 proved the native negative-Z strafe and wall convention. Production-world
# #664 now proves the same strafe can hand Create-native ownership from the request carriage to an
# authoritative sibling exactly one client tick later. The current wall verifier selects the actual
# supported three-tick same-carriage plateau directly, so retain that composition while reversing
# only the wall direction back to the negative-Z fixture convention. Verifier bookkeeping only.
wall_direction_replacements = [
    (
        'wall_geometry_seen = any(re.search(r"(?:^|\\|)-?\\d+, [123], 2(?:\\||$)", m.group(4)) for m in client_state_pattern.finditer(text))',
        'wall_geometry_seen = any(re.search(r"(?:^|\\|)-?\\d+, [123], -2(?:\\||$)", m.group(4)) for m in client_state_pattern.finditer(text))',
    ),
    (
        'if not wall_geometry_seen: raise SystemExit("M1 wall proof missing occupied carriage side geometry at local block z=2")',
        'if not wall_geometry_seen: raise SystemExit("M1 wall proof missing occupied carriage side geometry at local block z=-2")',
    ),
    (
        'start_z=start_sample[4]; wall_z=[s[4] for s in after]; max_z=max(wall_z)\nif max_z>=2.0: raise SystemExit(f"M1 player penetrated occupied carriage side geometry: local_z_samples={wall_z}")',
        'start_z=start_sample[4]; wall_z=[s[4] for s in after]; min_z=min(wall_z)\nif min_z<=-2.0: raise SystemExit(f"M1 player penetrated occupied carriage side geometry: local_z_samples={wall_z}")',
    ),
    (
        'strafe_requested_toward_wall = strafe_move is not None and float(strafe_move.group(3)) >= 0.02\nmaterial_approach = max_z-start_z >= 0.015',
        'strafe_requested_toward_wall = strafe_move is not None and float(strafe_move.group(3)) <= -0.02\nmaterial_approach = start_z-min_z >= 0.015',
    ),
    (
        'if stable_plateau and (max(candidate_z)-start_z>=0.015 or strafe_requested_toward_wall):',
        'if stable_plateau and (start_z-min(candidate_z)>=0.015 or strafe_requested_toward_wall):',
    ),
]
for old_wall, new_wall in wall_direction_replacements:
    if verifier_source.count(old_wall) != 1:
        raise SystemExit("M1 wall verifier expected one transformed current direction boundary: " + old_wall[:72])
    verifier_source = verifier_source.replace(old_wall, new_wall, 1)

# Older verifier compositions used an explicit sibling-handoff window here. Keep the bounded
# request-tick/+1 rewrite only when that legacy block is present. The current plateau selector
# already follows the authoritative sibling and must not be rewritten back to request-tick pinning.
late_handoff = r'''pre_wall_carriage=before[-1][1]
rebase_pattern=re.compile(
    rf"GATE_E_PHASE136_SUPPORTED_SIBLING_REBASE[^\n]*previous_carriage_id={pre_wall_carriage}[^\n]*carriage_id=(\d+)[^\n]*player_tick=(\d+)[^\n]*native_contact_owner=true[^\n]*identity_only=true")
rebase_match=next((m for m in rebase_pattern.finditer(text) if strafe_request_tick <= int(m.group(2)) <= strafe_request_tick+7), None)
wall_carriage=int(rebase_match.group(1)) if rebase_match is not None else pre_wall_carriage
wall_start_tick=int(rebase_match.group(2)) if rebase_match is not None else strafe_request_tick
after=[]; expected_tick=wall_start_tick
for sample in after_window:
    if sample[0]<expected_tick: continue
    if sample[0]!=expected_tick or sample[1]!=wall_carriage: break
    after.append(sample); expected_tick+=1
if len(after)<3: raise SystemExit("M1 wall proof did not retain three consecutive samples on the Create-authoritative strafe carriage")'''
bounded_handoff = r'''pre_wall_carriage=before[-1][1]
rebase_pattern=re.compile(
    rf"GATE_E_PHASE136_SUPPORTED_SIBLING_REBASE[^\n]*previous_carriage_id={pre_wall_carriage}[^\n]*carriage_id=(\d+)[^\n]*player_tick=(\d+)[^\n]*native_contact_owner=true[^\n]*identity_only=true")
rebase_match=next((m for m in rebase_pattern.finditer(text) if strafe_request_tick <= int(m.group(2)) <= strafe_request_tick+1), None)
wall_carriage=int(rebase_match.group(1)) if rebase_match is not None else pre_wall_carriage
wall_start_tick=int(rebase_match.group(2)) if rebase_match is not None else strafe_request_tick
after=[]; expected_tick=wall_start_tick
for sample in after_window:
    if sample[0]<expected_tick: continue
    if sample[0]!=expected_tick or sample[1]!=wall_carriage: break
    after.append(sample); expected_tick+=1
if len(after)<3: raise SystemExit("M1 wall proof did not retain three consecutive samples on the Create-authoritative strafe carriage")'''
if verifier_source.count(late_handoff) == 1:
    verifier_source = verifier_source.replace(late_handoff, bounded_handoff, 1)
elif not (
    'start_sample=pre_window[-1]' in verifier_source
    and 'three consecutive supported samples on one Create carriage during strafe' in verifier_source
):
    raise SystemExit("M1 wall verifier lost both legacy handoff and current plateau boundaries")

required = [
    'self.tickCount >= startTick + 4',
    'vs2$walkConfirmedTick = startTick + 4',
    'Boolean.getBoolean("vs2.productionFixtureWalkConfirmed")',
    'System.getProperty("vs2.productionFixtureWalkStartTick")',
    'if (!vs2$fixtureWalkSeen(self) || !vs2$backwardConfirmed) return false;',
    'self.setYRot(90.0F)',
    'boolean pulse = self.tickCount >= startTick + 1 && self.tickCount <= startTick + 3',
]
missing = [token for token in required if token not in source]
if missing:
    raise SystemExit("M1 input timing lost sequencing/negative-wall anchors: " + ", ".join(missing))
lease_required = [
    'vs2$traceContactLease("tail", true);',
    'vs2.phase170NativeContactApplicationTick.',
    'vs2.phase170NativeContactApplicationCarriageId',
    'Integer.toString(self.getId()).equals(vs2$activeNativeCarriage)',
    'vs2$recentNativeOwner',
    'vs2$airborneNativeLease = !player.onGround()',
    'vs2$groundedNativeLease = player.onGround()',
    'vs2$airborneNativeLease || vs2$groundedNativeLease',
    'method.invoke(lease, Integer.valueOf(2))',
]
lease_missing = [token for token in lease_required if token not in lease_source]
if lease_missing:
    raise SystemExit("M1 native lease lost active-frame identity anchors: " + ", ".join(lease_missing))
verifier_required = [
    'local block z=-2',
    'min_z=min(wall_z)',
    'float(strafe_move.group(3)) <= -0.02',
    'start_z-min(candidate_z)>=0.015',
]
if 'start_sample=pre_window[-1]' not in verifier_source:
    verifier_required.extend([
        'strafe_request_tick+1',
        'wall_start_tick=int(rebase_match.group(2))',
    ])
verifier_missing = [token for token in verifier_required if token not in verifier_source]
if verifier_missing:
    raise SystemExit("M1 wall verifier lost bounded native-handoff proof anchors: " + ", ".join(verifier_missing))
for forbidden in [
    'self.setPos(', 'self.setDeltaMovement(', 'self.move(', '.teleport(',
    'setBlock(', 'syncCarriage(', 'setVelocity(', 'method.invoke(lease, Integer.valueOf(0))',
]:
    if forbidden in walk_pulse_new + strafe_yaw_new + new + strafe_guard_new + lease_tail_new + lease_outer_guard_new + lease_airborne_new + lease_grounded_new + lease_grace_overlap_new:
        raise SystemExit("M1 input/lease patch introduced forbidden gameplay mutation: " + forbidden)

fixture_input.write_text(source, encoding="utf-8")
contact_lease.write_text(lease_source, encoding="utf-8")
verifier.write_text(verifier_source, encoding="utf-8")
print("M1 input timing: delays the actual fixture forward pulse one tick so standing carry proof completes before native locomotion")